Fix WebSocket crash when no authenticated user
Sentry doesn't seem to be working for the WebSocket currently (a
separate issue) so we don't have a crash report, but in the WebSocket's
logs I'm seeing this:

    AttributeError: 'NoneType' object has no attribute 'user'
    2025-09-18 12:45:40,652 [12] [h.streamer.db:WARNING] Caught exception during streamer transaction:
    Traceback (most recent call last):
      File "/var/lib/hypothesis/h/streamer/db.py", line 24, in read_only_transaction
        yield
      File "/var/lib/hypothesis/h/streamer/streamer.py", line 80, in process_work_queue
        messages.handle_message(msg, registry, session, TOPIC_HANDLERS)
      File "/var/lib/hypothesis/h/streamer/messages.py", line 77, in handle_message
        handler(message.payload, sockets, request, session)
      File "/var/lib/hypothesis/h/streamer/messages.py", line 127, in handle_annotation_event
        request, message, annotation, user=socket.identity.user

Fix the WebSocket's `handle_annotation_event()` function to work if
`socket.identity` is `None` or if `socket.identity.user` is `None`. This
should fix the crash.