Fix syntax error in gulpfile.js
It looks like backticks ` were used instead of ', resulting in:

    /.../h/gulpfile.js:33
        throw new Error(`Environment variable ${key} is not set`);
                        ^
    SyntaxError: Unexpected token ILLEGAL