Make User.email nullable
Usage:

    $ ./bin/hypothesis --dev shell
    >>> from __future__ import unicode_literals
    >>>
    >>> # You can add two users with the same authority and no email.
    >>> session.add(models.User(username="user1", authority="hypothes.is"))
    >>> session.add(models.User(username="user2", authority="hypothes.is"))
    >>> # Commit the transaction, no error:
    >>> request.tm.commit()

    >>> # You still can't add two users with the same authority and the
    >>> # same non-null email.
    >>> session.add(models.User(username="user3", authority="hypothes.is", email="me@me.com"))
    >>> session.add(models.User(username="user4", authority="hypothes.is", email="me@me.com"))
    >>> # You'll get an error when you try to commit the transaction.
    >>> # Note that because of a bug in the transaction library we're
    >>> # actually getting a TypeError here. But the underlying
    >>> # exception, which the transaction library is swallowing, is a
    >>> # database IntegrityError.
    >>> request.tm.commit()
    TypeError: 'unicode' does not have the buffer interface

    >>> # Querying.
    >>> session.query(models.User).all()
    [<User: user1>, <User: user2>, <User: user3>]

    >>> session.query(models.User).filter_by(email="me@me.com").all()
    [<User: user3>]

    >>> # SQLAlchemy handles the Postgres = NULL vs IS NULL stuff
    >>> # (see https://github.com/hypothesis/h/pull/5102 for notes)
    >>> # for us, so filter_by(email=None) works fine.
    >>> session.query(models.User).filter_by(email=None).all()
    [<User: user2>, <User: user1>]