Add scopes support to OpenGroup factory
Usage:

By default `factories.OpenGroup()` will return an unscoped open group:

    >>> group = factories.OpenGroup()
    >>> group.scopes
    []

You can pass in an int to make it create a number of randomly generated
scopes for the group:

    >>> group = factories.OpenGroup(scopes=2)
    >>> group.scopes
    [<GroupScope https://thomas.org/>, <GroupScope http://jones.com/>]

If you want to create an open group with a particular scope or scopes
you need to create an unscoped open group first then create the scopes:

    group = factories.OpenGroup()
    scope_1 = factories.GroupScope(group=group, ...)
    scope_2 = factories.GroupScope(group=group, ...)

Note that you have to be careful when trying to do it the other way
round:

    scope = factories.GroupScope()
    group = factories.OpenGroup(scopes=[scope])

This will leave an extra unscoped open group behind in the db: the first
call to `factories.GroupScope()` wq creates a randomly generated open group
for the scope to belong to, then the second call to `factories.OpenGroup()`
_moves_ the scope from the first group to the second, but still leaves
the scope's original generated group behind in the DB.

This won't work either:

    >>> scope = factories.GroupScope(group=None)
    >>> group = factories.OpenGroup(scopes=[scope])
    IntegrityError: (psycopg2.IntegrityError) null value in column "group_id" violates not-null constraint

Some code get triggered that attempts to flush the `GroupScope` while
its `group` is still `None`m which is invalid.

You **can** do it with `build()`, like this:

    >>> scope = factories.GroupScope.build(group=None)
    >>> group = factories.OpenGroup(scopes=[scope])