Upgrade ws4py to prevent crash on client disconnect (#4563)
Currently we're seeing a fair number of websocket server crashes in the
logs:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
        result = self._run(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/ws4py/websocket.py", line 506, in run
        if not self.once():
      File "/usr/lib/python2.7/site-packages/ws4py/websocket.py", line 388, in once
        if not self.process(b):
      File "/usr/lib/python2.7/site-packages/ws4py/websocket.py", line 445, in process
        self.close(s.closing.code, s.closing.reason)
      File "/usr/lib/python2.7/site-packages/ws4py/websocket.py", line 189, in close
        self._write(self.stream.close(code=code, reason=reason).single(mask=self.stream.always_mask))
      File "/usr/lib/python2.7/site-packages/ws4py/websocket.py", line 279, in _write
        self.sock.sendall(b)
      File "/usr/lib/python2.7/site-packages/gevent/_socket2.py", line 419, in sendall
        timeleft = self.__send_chunk(chunk, flags, timeleft, end)
      File "/usr/lib/python2.7/site-packages/gevent/_socket2.py", line 355, in __send_chunk
        data_sent += self.send(chunk, flags)
      File "/usr/lib/python2.7/site-packages/gevent/_socket2.py", line 323, in send
        return sock.send(data, flags)
    error: [Errno 32] Broken pipe
    Tue May 16 16:23:47 2017 <Greenlet at 0x7ff257b3ac30: <bound method WebSocket.run of <h.streamer.websocket.WebSocket object at 0x7ff257a10f90>>> failed with error

These appear to be caused by an abrupt disconnection of a websocket
client without the receipt of a closing handshake. Unfortunately this
appears to be a behaviour associated with AWS ALBs, and isn't something
we can easily remedy. We should not crash in this case.

The underlying problem would appear to be
[Lawouach/WebSocket-for-Python#150][1], which was [fixed][2] in ws4py's
0.4.0 release.

This commit updates us to the latest release of ws4py.

[1]: https://github.com/Lawouach/WebSocket-for-Python/issues/150
[2]: https://github.com/Lawouach/WebSocket-for-Python/commit/7668d39d8678618accbd2d18e25a456f99738dbf